name: Deploy to Server

on:
  push:
    branches:
      - main # 当推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用 Ubuntu 系统运行

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Trust Server Host Key
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh
          # 提取主机部分（去除 root@）
          HOST=$(echo "$SSH_HOST" | sed 's/.*@//')
          echo "Scanning host key for: $HOST"
          ssh-keyscan "$HOST" >> ~/.ssh/known_hosts

      - name: Upload files via rsync
        run: |
          rsync -avz --delete ./dist/ ${{ secrets.SSH_HOST }}:/var/www/my-site/
